---
- name: " Create Key SSH"
  hosts: all
  become: yes
  tasks:
    - name: "Create a 2048-bit SSH key for user User3 in ~user3/.ssh/id_rsa"
      user:
        name: user3
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
...
