---
- name: " Remove User"
  hosts: all
  become: yes
  tasks:
    - name:  "remove user1'"
      user:
        name: user1
        state: absent
        remove: yes
    - name: "remove user2"
      user:
        name: user2
        state: absent
        remove: yes
...

